### ISSUE TITLE
好像會有 re-render 的問題

### ISSUE THREAD

**Issue by david-zw-liu** [realdennis/nonaction#2]
https://codesandbox.io/s/5027vmyq6p

您好，
我把範例稍微改了一下，
如果 FlagContainer 的 state 改變了，
會造成 CounterPanel Component re-render 的樣子，
我之前也有嘗試用 react context 做單一 state 也有遇到這個問題。

不知道是不是我哪裡有做錯了？
謝謝

**Comment by realdennis** [comment]
根據 react 文檔所提到：
> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes.

你沒有做錯，只要是透過 Context API 建立出來的 Provider state 改變都會讓 Consumer Re-render，不管是這個函式庫也好，還是用原生的 Context 也好都會發生re-render的問題。未來會再參考一下Redux的[`CombineReducers`](https://github.com/reduxjs/redux/blob/6949ba0ce1d25aca9fa40d250d81c7e09beff30f/src/combineReducers.js#L115) 、react-reudx 的 `connect`/ [`connectAdvanced`](https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js) 的方法看能不能再做優化。

**Comment by david-zw-liu** [comment]
Ok, thank you
